# Configuración básica del sitio
title: Mejora de tus Inferencias Estadísticas
email: tu_correo_electronico@ejemplo.com # Reemplaza con tu correo
description: >-
  Traducción al castellano del recurso educativo abierto "Improving Your Statistical Inferences"
  de Daniël Lakens. Contiene información para mejorar la inferencia estadística,
  diseñar mejores experimentos e informar la investigación científica de forma más transparente.
baseurl: "/inferencias-estadisticas-eESP" # Reemplaza "inferencias-estadisticas-es" con el nombre de tu repositorio
url: "https://juangff85.github.io" # Reemplaza con tu usuario de GitHub

# Configuración de Jekyll
markdown: kramdown
theme: minima # Minima es un tema estándar de GitHub Pages.
# El autor original usa un tema más complejo que no es Minima,
# pero Minima nos sirve para empezar y construir los archivos básicos.
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir archivos innecesarios
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
