# Configuración básica del sitio (Mantener esta parte)
title: Mejora de tus Inferencias Estadísticas
description: >-
  Traducción al castellano por Juan G. Fernández del recurso abierto "Improving Your Statistical Inferences"
  de Daniël Lakens.
baseurl: "/inferencias-estadisticas-ESP"
url: "https://juangff85.github.io" 

# Configuración de Jekyll y Tema (¡Copia este bloque!)
markdown: kramdown
theme: just-the-docs 

# 2. Añade los plugins que el tema Just the Docs requiere
plugins:
  - jekyll-feed
  - jekyll-sitemap
# --------------------
