# Configuración básica del sitio
title: Mejora de tus Inferencias Estadísticas
description: >-
  Traducción al castellano por Juan G. Fernández del recurso abierto "Improving Your Statistical Inferences"
  de Daniël Lakens. Contiene información para mejorar la inferencia estadística,
  diseñar mejores experimentos e informar la investigación científica de forma más transparente.
baseurl: "/inferencias-estadisticas-ESP" # Reemplaza "inferencias-estadisticas-es" con el nombre de tu repositorio
url: "https://juangff85.github.io" # Reemplaza con tu usuario de GitHub

# Configuración de Jekyll
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  # Configura el título que aparece en la barra superior
title: Mejora de tus Inferencias Estadísticas

# Oculta el enlace 'Edit this Page' si no quieres que aparezca
gh_edit_link: false

# Configura el color de la barra lateral (dark, light, o color)
color_scheme: light

# Excluir archivos innecesarios
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
